JBBar-Helpy/config/routes.rb
Rails.application.routes.draw do


  root to: "locales#redirect_on_locale"

  devise_for :users, skip: [:password, :registration, :confirmation, :invitations], controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  as :user do
    get "/users/invitation/accept" => "devise/invitations#edit", as: :accept_user_invitation
    post "/users/invitation" => "devise/invitations#create", as: :user_invitation
    put "/users/invitation" => "devise/invitations#update", as: nil
    patch "/users/invitation" => "devise/invitations#update", as: nil
  end

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  localized do

    root to: "home#index"

    get 'omniauth/:provider' => 'omniauth#localized', as: :localized_omniauth

    #devise_for :users, controllers: {
    #      registrations: 'registrations',
    #      omniauth_callbacks: "callbacks"
    #    }

    match 'users/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
    devise_for :users, skip: [:omniauth_callbacks, :invitations], controllers: { registrations: 'registrations', sessions: 'sessions', passwords: 'passwords' }

    as :user do
      get "/users/invitation/accept" => "devise/invitations#edit", as: :accept_user_invitation
      post "/users/invitation" => "devise/invitations#create", as: :user_invitation
      put "/users/invitation" => "devise/invitations#update", as: nil
      patch "/users/invitation" => "devise/invitations#update", as: nil
    end

    resources :knowledgebase, :as => 'categories', :controller => "categories", except: [:new, :edit, :create, :update] do
      resources :docs, except: [:new, :edit, :create, :update]
    end

    resources :docs, except: [:new, :edit] do
      resources :comments, only: :create
    end
    resources :community, :as => 'forums', :controller => "forums" do
      resources :topics
    end
    resources :topics do
      resources :posts
    end
    resources :posts do
      resources :flags, only: [:create]
    end

    post 'topic/:id/vote' => 'topics#up_vote', as: :up_vote, defaults: { format: 'js' }
    post 'post/:id/vote' => 'posts#up_vote', as: :post_vote, defaults: { format: 'js' }
    get 'thanks' => 'topics#thanks', as: :topic_thanks
    get 'result' => 'result#index', as: :result
    get 'search' => 'result#search', as: :search
    get 'tickets' => 'topics#tickets', as: :tickets
    get 'ticket/:id/' => 'topics#ticket', as: :ticket
    get 'locales/select' => 'locales#select', as: :select_locale
  end

  get '/switch_locale' => 'home#switch_locale', as: :switch_locale

  # Widget Routes
  get 'widget' => 'widget/topics#new', as: :widget
  namespace :widget do
    get 'index' => 'topics#new', as: :widget
    post 'topics' => 'topics#create', as: :create
    get 'topics/thanks' => 'topics#thanks', as: :thanks
  end

  # Webhook Routes
  namespace :webhook do
    post 'form/:token' => 'inbound#form', as: :form
  end

  # Admin Routes

  namespace :admin do

    # Extra topic Routes
    get 'topics/update_topic' => 'topics#update_topic', as: :update_topic, defaults: {format: 'js'}
    post 'topics/merge_tickets' => 'topics#merge_tickets', as: :merge_tickets
    patch 'topics/update_tags' => 'topics#update_tags', as: :update_topic_tags
    get 'topics/update_multiple' => 'topics#update_multiple_tickets', as: :update_multiple_tickets
    get 'topics/assign_agent' => 'topics#assign_agent', as: :assign_agent
    get 'topics/toggle_privacy' => 'topics#toggle_privacy', as: :toggle_privacy
    get 'topics/:id/toggle' => 'topics#toggle_post', as: :toggle_post
    get 'topics/assign_team' => 'topics#assign_team', as: :assign_team
    post 'topics/:topic_id/split/:post_id' => 'topics#split_topic', as: :split_topic
    get 'shortcuts' => 'topics#shortcuts', as: :shortcuts

    # SearchController Routes
    get 'search/topic_search' => 'search#topic_search', as: :topic_search

    # Settings Routes
    get 'settings' => 'settings#index', as: :settings
    get 'settings/preview' => 'settings#preview', as: :preview
    put 'update_settings/' => 'settings#update_settings', as: :update_settings
    get 'settings/general' => 'settings#general', as: :general_settings
    get 'settings/design' => 'settings#design', as: :design_settings
    get 'settings/theme' => 'settings#theme', as: :theme_settings
    get 'settings/widget' => 'settings#widget', as: :widget_settings
    get 'settings/i18n' => 'settings#i18n', as: :i18n_settings
    get 'settings/email' => 'settings#email', as: :email_settings
    get 'settings/integration' => 'settings#integration', as: :integration_settings
    get 'settings/profile' => 'settings#profile', as: :profile_settings

    get 'notifications' => 'settings#notifications', as: :notifications
    put 'update_notifications' => 'settings#update_notifications', as: :update_notifications

    # Onboarding Routes
    get '/onboarding/index' => 'onboarding#index', as: :onboarding
    patch '/onboarding/update_user' => 'onboarding#update_user', as: :onboard_user
    patch '/onboarding/update_settings' => 'onboarding#update_settings', as: :onboard_settings
    get '/onboarding/complete' => 'onboarding#complete', as: :complete_onboard

    # Misc Routes
    post 'shared/update_order' => 'shared#update_order', as: :update_order
    get 'cancel_edit_post/:id/' => 'posts#cancel', as: :cancel_edit_post
    get 'users/invite' => 'users#invite', as: :invite
    put 'users/invite_users' => 'users#invite_users', as: :invite_users

    post 'posts/users' => 'posts#search', as: :user_search
    get  'posts/new_user' => 'posts#new_user', as: :new_user
    post  'posts/new_user' => 'posts#change_owner_new_user'

    resources :categories do
      resources :docs, except: [:index, :show]
    end
    resources :docs, except: [:index, :show]

    resources :images, only: [:create, :destroy]
    resources :forums# , except: [:index, :show]
    resources :users
    scope 'settings' do
      resources :api_keys, except: [:show, :edit, :update]
      resources :groups
    end
    resources :topics, except: [:delete, :edit] do
      resources :posts
    end
    resources :posts
    get '/posts/:id/raw' => 'posts#raw', as: :post_raw
    get '/dashboard' => 'dashboard#index', as: :dashboard
    get '/reports/team' => 'reports#team', as: :team_reports
    get '/reports/groups' => 'reports#groups', as: :group_reports
    get '/reports' => 'reports#index', as: :reports

    root to: 'dashboard#index'
  end

  mount API::Base, at: "/"
  mount GrapeSwaggerRails::Engine => '/api/v1/api_doc'

  # Receive email from Griddler
  mount_griddler

  # Mount attachinary
  mount Attachinary::Engine => "/attachinary"

end

JBBar-Helpy/app/controllers/admin/posts_controller.rb
class Admin::PostsController < Admin::BaseController

  before_action :verify_agent
  respond_to :js

  def edit
    @post = Post.where(id: params[:id]).first
  end

  def cancel
    @post = Post.where(id: params[:id]).first
  end

  def create
    @topic = Topic.find(params[:topic_id])
    # @post = Post.new(:body => params[:post][:body],
    #                  :topic_id => @topic.id,
    #                  :user_id => current_user.id,
    #                  :kind => params[:post][:kind],
    #                  :screenshots => params[:post][:screenshots])

    @post = Post.new(post_params)
    @post.topic_id = @topic.id
    @post.user_id = current_user.id
    get_all_teams
    
    respond_to do |format|
      if @post.save
        format.html {
          redirect_to admin_topic_path(@post.topic_id)
        }
        format.js {
          if params[:post][:resolved] == "1"
            @topic.close(current_user.id)
            tracker("Agent: #{current_user.name}", "Closed", @topic.to_param) #TODO: Need minutes
          end
          fetch_counts
          @posts = @topic.posts.chronologic

          @admins = User.agents
          #@post = Post.new
          case @post.kind
          when "reply"
            tracker("Agent: #{current_user.name}", "Agent Replied", @topic.to_param) #TODO: Need minutes
          when "note"
            tracker("Agent: #{current_user.name}", "Agent Posted Note", @topic.to_param) #TODO: Need minutes
          end
          render 'admin/topics/show'
        }
      else
        format.html { render :action => "new" }
        format.js {
          render 'admin/topics/show'
        }
      end
    end
  end

  def update
    @post = Post.find(params[:id])
    old_user = @post.user

    fetch_counts
    get_all_teams
    @topic = @post.topic
    @posts = @topic.posts.chronologic

    if @post.update_attributes(post_params)
      update_topic_owner(old_user, @post) if @post.kind == 'first'
      respond_to do |format|
        format.js {}
      end
    else
      render json: nil, status: 404
      logger.info("error")
    end
  end

  def search
    search_string = params[:user_search]
    @post_id = params[:post_id]
    @users = User.user_search(search_string)
    @users = nil if search_string.blank? || @users.empty?
  end

  def new_user
    @post_id = params[:post_id]
    @user = User.new
  end

  def change_owner_new_user
    @post = Post.find(params[:post_id])
    old_user = @post.user

    fetch_counts
    get_all_teams
    @topic = @post.topic
    @posts = @topic.posts.chronologic

    # Check user doesnt exist
    @user = User.find_by(email: params[:user][:email])

    # create user
    if @user.nil?
      @user = User.new

      @token, enc = Devise.token_generator.generate(User, :reset_password_token)
      @user.reset_password_token = enc
      @user.reset_password_sent_at = Time.now.utc

      @user.name = params[:user][:name]
      @user.login = params[:user][:email].split("@")[0]
      @user.email = params[:user][:email]
      @user.password = User.create_password
    end

    # assign user
    if @user.save && @post.update(user: @user)
      update_topic_owner(old_user, @post) if @post.kind == 'first'
    end

    # re render topic
    render 'admin/posts/update'
  end

  def raw
    @post = Post.find(params[:id])
    render layout: false
  end

  private

  def post_params
    params.require(:post).permit(
      :body,
      :kind,
      {screenshots: []},
      {attachments: []},
      :cc,
      :bcc,
      :user_id,
    )
  end

  def update_topic_owner(old_owner, post)
      return if old_owner == post.user

      topic = post.topic
      topic.update(user: post.user)
      topic.posts.create(
        user: current_user,
        body: I18n.t('change_owner_note', old: old_owner.name, new: post.user.name, default: "The creator of this topic was changed from #{old_owner.name} to #{post.user.name}"),
        kind: "note",
      )

  end
end

JBBar-Helpy/app/controllers/api/v1/posts.rb
module API
  module V1
    class Posts < Grape::API

      before do
        authenticate!
        restrict_to_role %w(admin agent)
      end

      include API::V1::Defaults
      resource :posts, desc: "Post replies to topics" do

        # throttle max: 200, per: 1.minute

        # CREATE NEW POST. THIS REPLIES TO BOTH COMMUNITY TOPICS AND PRIVATE TICKETS
        desc "Add a new reply to an existing discussion"
        params do
          requires :topic_id, type: Integer, desc: "Topic to add post to"
          requires :body, type: String, desc: "The post body"
          requires :user_id, type: Integer, desc: "The User ID of the poster"
          requires :kind, type: String, desc: "The kind of post, either 'reply' or 'note'"
          optional :cc, type: String, desc: "Comma separated list of emails to CC"
          optional :bcc, type: String, desc: "Comma separated list of emails to BCC"
        end
        post "", root: :posts do
          post = Post.create!(
            topic_id: permitted_params[:topic_id],
            body: permitted_params[:body],
            user_id: permitted_params[:user_id],
            kind: permitted_params[:kind],
            cc: permitted_params[:cc],
            bcc: permitted_params[:bcc]
          )
          present post, with: Entity::Post
        end

        # UPDATE POST. THIS REPLIES TO BOTH COMMUNITY TOPICS AND PRIVATE TICKETS
        desc "Update a post"
        params do
          requires :id, type: Integer, desc: "The Post ID"
          requires :body, type: String, desc: "The post body"
          requires :active, type: Boolean, desc: "Whether the post is live or not"
        end
        patch ":id", root: :posts do
          post = Post.find(permitted_params[:id])
          post.update!(
            body: permitted_params[:body],
            active: permitted_params[:active]
          )
          present post, with: Entity::Post
        end


      end
    end
  end
end

JBBar-Helpy/app/controllers/posts_controller.rb
# == Schema Information
#
# Table name: posts
#
#  id          :integer          not null, primary key
#  topic_id    :integer
#  user_id     :integer
#  body        :text
#  kind        :string
#  active      :boolean          default(TRUE)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  points      :integer          default(0)
#  attachments :string           default([]), is an Array
#  cc          :string
#  bcc         :string
#  raw_email   :text
#

class PostsController < ApplicationController

  # Make sure forums are enabled
  before_action :forums_enabled?, only: ['index','show']

  respond_to :js, only: [:up_vote]
  layout "clean", only: :index
  theme :theme_chosen

  def index
    @topic = Topic.undeleted.ispublic.where(id: params[:topic_id]).first#.includes(:forum)
    if @topic
      @posts = @topic.posts.ispublic.active.all.chronologic.includes(:user)
      @post = @topic.posts.new
      @page_title = "#{@topic.name}"
      add_breadcrumb t(:community, default: "Community"), forums_path
      add_breadcrumb @topic.forum.name, forum_topics_path(@topic.forum)
      add_breadcrumb @topic.name
    end

    redirect_to root_path unless @topic
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @post = @topic.posts.new(post_params)
    @post.topic_id = @topic.id
    @post.user_id = current_user.id
    @post.screenshots = params[:post][:screenshots]

    respond_to do |format|
      if @post.save
        format.html {
          @posts = @topic.posts.ispublic.chronologic.active
          if @topic.public?
            # This is a forum post
            redirect_to @topic.doc.nil? ? topic_posts_path(@topic.id) : doc_path(@topic.doc_id)
          else
            # This post belongs to a ticket
            agent = User.find(@topic.assigned_user_id)
            tracker("Agent: #{agent.name}", "User Replied", @topic.to_param) #TODO: Need minutes
            redirect_to ticket_path(@topic.id)
          end
        }
        format.js {
          @posts = @topic.posts.ispublic.chronologic.active
          unless @topic.assigned_user_id.nil?
            agent = User.find(@topic.assigned_user_id)
            tracker("Agent: #{agent.name}", "User Replied", @topic.to_param) #TODO: Need minutes
          end
        }
      else
        format.html { render :action => "new" }
      end
    end
  end

  def up_vote
    if user_signed_in?
      @post = Post.find(params[:id])
      @post.votes.create(user_id: current_user.id)
      @topic = @post.topic
      @topic.touch
      @post.reload
    end
  end

  def post_params
    params.require(:post).permit(
      :body,
      :kind,
      {attachments: []}
    )
  end

end

JBBar-Helpy/app/helpers/posts_helper.rb
# == Schema Information
#
# Table name: posts
#
#  id          :integer          not null, primary key
#  topic_id    :integer
#  user_id     :integer
#  body        :text
#  kind        :string
#  active      :boolean          default(TRUE)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  points      :integer          default(0)
#  attachments :string           default([]), is an Array
#  cc          :string
#  bcc         :string
#  raw_email   :text
#

module PostsHelper

  def post_message(post,admin=false)

    case post.kind
    when 'first'
      message = t(:asked_a_question, user_name: post.user.name.titleize ,default: "asked a question...")
    when 'reply'
      message = t(:replied, user_name: post.user.name.titleize, default: "replied...")
    when 'note'
      message = t(:posted_note, user_name: post.user.name.titleize, default: "posted an internal note...")
    end
    if admin
      content_tag(:span, class: 'btn dropdown-toggle more-important post-dropdown', data: { toggle: 'dropdown'}, aria: {expanded: 'false'}) do
        "#{message} <span class='caret'></span>".html_safe
      end
    else
      content_tag(:span, class: 'more-important') do
        "#{message}".html_safe
      end
    end
  end

  def vote_widget(topic)
    content_tag(:div, class: "voting-widget") do
      content_tag(:div, class: "vote-icon glyphicon glyphicon-chevron-up")
      content_tag(:div, class: "topic_points") do
        link_to topic.points, up_vote_path(topic.id), method: :post, remote: true
      end
    end
  end

  def post_admin

  end

end

JBBar-Helpy/app/views/posts/_attachment.html.erb
<%
################################################################################
# NOTE: It is STRONGLY suggested that if you wish to customize the look and feel
# of your Helpy, that you create a custom theme instead.  This will allow
# you to override any views or styles you wish to, without compromising your
# ability to upgrade in the future
################################################################################
%>

<!-- attachments thumbnail partial -->
<%= content_tag(:div, id: 'post-images')  do %>
  <%= content_tag(:ul, class: 'list-inline') do %>
    <% model_name.attachments.each do |att| %>
      <%= content_tag(:li, class: "#{%w(png jpg jpeg gif).include?(att.file.extension) ? 'image' : 'raw'}") do %>
        <% if %w(png jpg jpeg gif).include?(att.file.extension) %>
          <%= link_to image_tag(att, style: "width: 125px; height: 125px"), att.url, class: 'screenshot-link', target: 'blank' %>
        <% else %>
          <%= link_to att.url, title: att.url, target: 'blank' do %>
            <%= content_tag(:i, '', class: attachment_icon(att.url)) %>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

JBBar-Helpy/app/views/posts/_flag.html.erb
<%= link_to t(:flag_for_review), '#', data: {toggle: "modal", target: user_signed_in? ? "#flag-modal" : "#login-modal"} %>

JBBar-Helpy/app/views/posts/_post.html.erb
<%
################################################################################
# NOTE: It is STRONGLY suggested that if you wish to customize the look and feel
# of your Helpy, that you create a custom theme instead.  This will allow
# you to override any views or styles you wish to, without compromising your
# ability to upgrade in the future
################################################################################
%>

<!-- standard post partial -->
<div id="post-<%= post.id %>" class="media post-container <%= "kind-#{post.kind}" %><%= post.topic.forum.allow_post_voting? ? "" : " disallow-post-voting" %><%= " inactive" unless post.active? %>">
	<div class="pull-left">
		<%= avatar_image(post.user, size=40) %>
	</div>
	<div class="media-body media-right">
		<span class="hidden-sm hidden-md hidden-lg"><%= last_active_time(post.created_at) %><br/></span>
		<span id="row-<%= post.id %>"  class="post-menu post-menu-<%= post.id %> btn-group">
			<%= post_message(post) %>
		</span>

		<span class="last-active posted-at less-important pull-right">
			<span class="hidden-xs">
				<%= last_active_time(post.created_at) %>
			</span>
		</span>

		<div id="post-body-<%= post.id %>" class="post-body less-important text-left text-content">
			<%= simple_format(post.body) -%>
			<% if post.topic.forum.allow_post_voting == true %>
			<div id="post-vote-<%= post.id %>" class="btn btn-default">
				<% if post.kind == 'first' %>
				<%= link_to t(:upvote, count: post.topic.points), up_vote_path(post.topic.id), method: :post, remote: true, class: 'topic-vote', data: {voted: post.topic.to_param}, id: "upvote_#{post.topic.id}" %>
				<% else %>
				<%= link_to t(:upvote, count: post.points), post_vote_path(post.id), method: :post, remote: true, class: 'post-vote', data: {voted: post.id}, id: "upvote_#{post.id}"  %>
				<% end %>
			</div>
			<% end %>
			<div class="public-post-options pull-right less-important">
				<%= render :partial => 'posts/flag' if post.topic.public? %>
			</div>
      <%= render partial: 'posts/thumbnail', locals: { :model_name => post } %>
      <%= render partial: 'posts/attachment', locals: { :model_name => post } %>
    </div>

		<% if user_signed_in? && post.kind == 'first' && post.topic.forum.allow_post_voting == true %>
			<div class="add-form inline-reply">
			<h4><%= t(:reply) %></h4>
			<%= bootstrap_form_for :post, :url => topic_posts_path(@topic) do |f| -%>
			  <%= f.text_area :body, :rows => 4, :cols => 160, label: 'Type your response:' -%></p>
			  <%= f.hidden_field 'kind', value: 'reply' %>
				<div class="add-screenshots">
				<%= attachinary_file_field_tag 'post[screenshots]', @topic.posts.new, :screenshots if cloudinary_enabled? %>
				</div>
				<% unless cloudinary_enabled? %>
					<%= f.file_field :attachments, multiple: true %>
					<ul class="list-inline" id="attachments">
						<%= render partial: 'posts/attachment', locals: { :model_name => post } %>
					</ul>
				<% end %>
				<%= hidden_field_tag :client_id %>
				<%= f.submit t(:submit_reply), class: 'btn btn-warning' -%>
			<% end -%>
			</div>
		<% end -%>

	</div>
</div>

<div id="flag-modal" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><%= t(:flag_post_for_review, default: "Flag For Review") %></h4>
      </div>

      <div class="modal-body row">
        <div class="col-md-12">
        <%= bootstrap_form_for :flag, :url => post_flags_path(post) do |f| -%>
          <%= f.text_area :reason, rows: 6, cols: 160, placeholder: t(:flag_post_placeholder), skip_label: true -%>
          <%= f.submit t(:flag, default: "Flag"), class: 'btn btn-warning' -%>
        <% end -%>
        </div>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

JBBar-Helpy/app/views/posts/_thumbnail.html.erb
<%
################################################################################
# NOTE: It is STRONGLY suggested that if you wish to customize the look and feel
# of your Helpy, that you create a custom theme instead.  This will allow
# you to override any views or styles you wish to, without compromising your
# ability to upgrade in the future
################################################################################
%>

<!-- screenshots thumbnail partial -->
<%= content_tag(:div, id: 'post-images')  do %>
    <%= content_tag(:ul, class: 'list-inline') do %>
        <%- model_name.screenshots.each do |screenshot| %>
          <%= content_tag(:li, class: screenshot.resource_type) do %>
            <% if Cloudinary.config.cloud_name.present? && screenshot.resource_type == "raw" %>
                <%= link_to "https://res.cloudinary.com/#{Cloudinary.config.cloud_name}/raw/upload/#{screenshot.path}", title: screenshot.path, target: 'blank' do %>
                  <%= content_tag(:i, '', class: attachment_icon(screenshot.path)) %>
                <% end %>
            <% elsif Cloudinary.config.cloud_name.present? %>
              <%= link_to cl_image_tag(get_path(screenshot), { size: '125x125', crop: :fit }), "https://res.cloudinary.com/#{Cloudinary.config.cloud_name}/image/upload/#{screenshot.path}", class: 'screenshot-link', target: 'blank' %>
            <% end %>
          <% end %>
        <% end %>
    <% end %>
<% end %>

JBBar-Helpy/app/views/posts/create.js.erb
$('#posts').append('<%= j render(partial: 'post', locals: { post: @post }) %>');

// Update timestamps
$('.last-active time[data-time-ago]').timeago();
$('.profile').initial();
// jQuery hook
//Helpy.ready();
//Helpy.track();
$('#new_post')[0].reset();

JBBar-Helpy/app/views/posts/index.html.erb
<%
################################################################################
# NOTE: It is STRONGLY suggested that if you wish to customize the look and feel
# of your Helpy, that you create a custom theme instead.  This will allow
# you to override any views or styles you wish to, without compromising your
# ability to upgrade in the future
################################################################################
%>

<% title "#{AppSettings['settings.site_name']}: #{@page_title}" %>

<div class="row">
	<div class="col-md-12">
		<script>
			Helpy.messages = '<%= j t(:collapsed_messages, count: @posts.count-2) %>';
		</script>

		<div id="posts">
			<%= render :partial => 'post', :collection => @posts %>
		</div>
		<%
		# NOTE: this is a bit of confusing logic- basically if the forum does not
		# allow reply (post) voting, the form should be shown beneath all posts.
		# This is handled here.  However, if there is post voting enabled,
		# it will render immediately after the first post, within the partial.
		%>
		<% if user_signed_in? && @topic.forum.allow_post_voting == false %>
			<div class="add-form">
			<h4><%= t(:reply) %></h4>
			<%#= error_messages_for :post -%>
			<%= bootstrap_form_for :post, :url => topic_posts_path(@topic) do |f| -%>
			  <%= f.text_area :body, :rows => 8, :cols => 160, label: 'Type your response:', class: 'disable-empty' -%></p>
			  <%= f.hidden_field 'kind', value: 'reply' %>
				<div class="add-screenshots">
				<%= attachinary_file_field_tag 'post[screenshots]', @post, :screenshots if cloudinary_enabled? %>
				</div>
				<% unless cloudinary_enabled? %>
					<%= f.file_field :attachments, multiple: true %>
					<ul class="list-inline" id="attachments">
						<%= render partial: 'posts/attachment', locals: { :model_name => @post } %>
					</ul>
				<% end %>
				<%= hidden_field_tag :client_id %>
				<%= f.submit t(:submit_reply), class: 'btn btn-warning disableable', disabled: 'disabled' -%>
			<% end -%>
			</div>
		<% else %>
			<% unless user_signed_in? %>
			<span id="reply-button" class="hidden-xs pull-right"><%= link_to t(:reply, default: "Reply"), '#', data: {toggle: "modal", target: "#login-modal"}, class: 'btn btn-primary' %></span>
			<% end %>
		<% end -%>

	</div>

</div>

JBBar-Helpy/app/views/posts/up_vote.js.erb
<% if user_signed_in? %>
$('#post-<%= @post.id %>').replaceWith("<%= j(render partial: 'posts/post', locals: {post: @post}) %>");
$('.profile').initial();
<% else %>
$('.login-link').click();
<% end %>