JBBar-Helpy/config/routes.rb
Rails.application.routes.draw do


  root to: "locales#redirect_on_locale"

  devise_for :users, skip: [:password, :registration, :confirmation, :invitations], controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  as :user do
    get "/users/invitation/accept" => "devise/invitations#edit", as: :accept_user_invitation
    post "/users/invitation" => "devise/invitations#create", as: :user_invitation
    put "/users/invitation" => "devise/invitations#update", as: nil
    patch "/users/invitation" => "devise/invitations#update", as: nil
  end

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all

  localized do

    root to: "home#index"

    get 'omniauth/:provider' => 'omniauth#localized', as: :localized_omniauth

    #devise_for :users, controllers: {
    #      registrations: 'registrations',
    #      omniauth_callbacks: "callbacks"
    #    }

    match 'users/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
    devise_for :users, skip: [:omniauth_callbacks, :invitations], controllers: { registrations: 'registrations', sessions: 'sessions', passwords: 'passwords' }

    as :user do
      get "/users/invitation/accept" => "devise/invitations#edit", as: :accept_user_invitation
      post "/users/invitation" => "devise/invitations#create", as: :user_invitation
      put "/users/invitation" => "devise/invitations#update", as: nil
      patch "/users/invitation" => "devise/invitations#update", as: nil
    end

    resources :knowledgebase, :as => 'categories', :controller => "categories", except: [:new, :edit, :create, :update] do
      resources :docs, except: [:new, :edit, :create, :update]
    end

    resources :docs, except: [:new, :edit] do
      resources :comments, only: :create
    end
    resources :community, :as => 'forums', :controller => "forums" do
      resources :topics
    end
    resources :topics do
      resources :posts
    end
    resources :posts do
      resources :flags, only: [:create]
    end

    post 'topic/:id/vote' => 'topics#up_vote', as: :up_vote, defaults: { format: 'js' }
    post 'post/:id/vote' => 'posts#up_vote', as: :post_vote, defaults: { format: 'js' }
    get 'thanks' => 'topics#thanks', as: :topic_thanks
    get 'result' => 'result#index', as: :result
    get 'search' => 'result#search', as: :search
    get 'tickets' => 'topics#tickets', as: :tickets
    get 'ticket/:id/' => 'topics#ticket', as: :ticket
    get 'locales/select' => 'locales#select', as: :select_locale
  end

  get '/switch_locale' => 'home#switch_locale', as: :switch_locale

  # Widget Routes
  get 'widget' => 'widget/topics#new', as: :widget
  namespace :widget do
    get 'index' => 'topics#new', as: :widget
    post 'topics' => 'topics#create', as: :create
    get 'topics/thanks' => 'topics#thanks', as: :thanks
  end

  # Webhook Routes
  namespace :webhook do
    post 'form/:token' => 'inbound#form', as: :form
  end

  # Admin Routes

  namespace :admin do

    # Extra topic Routes
    get 'topics/update_topic' => 'topics#update_topic', as: :update_topic, defaults: {format: 'js'}
    post 'topics/merge_tickets' => 'topics#merge_tickets', as: :merge_tickets
    patch 'topics/update_tags' => 'topics#update_tags', as: :update_topic_tags
    get 'topics/update_multiple' => 'topics#update_multiple_tickets', as: :update_multiple_tickets
    get 'topics/assign_agent' => 'topics#assign_agent', as: :assign_agent
    get 'topics/toggle_privacy' => 'topics#toggle_privacy', as: :toggle_privacy
    get 'topics/:id/toggle' => 'topics#toggle_post', as: :toggle_post
    get 'topics/assign_team' => 'topics#assign_team', as: :assign_team
    post 'topics/:topic_id/split/:post_id' => 'topics#split_topic', as: :split_topic
    get 'shortcuts' => 'topics#shortcuts', as: :shortcuts

    # SearchController Routes
    get 'search/topic_search' => 'search#topic_search', as: :topic_search

    # Settings Routes
    get 'settings' => 'settings#index', as: :settings
    get 'settings/preview' => 'settings#preview', as: :preview
    put 'update_settings/' => 'settings#update_settings', as: :update_settings
    get 'settings/general' => 'settings#general', as: :general_settings
    get 'settings/design' => 'settings#design', as: :design_settings
    get 'settings/theme' => 'settings#theme', as: :theme_settings
    get 'settings/widget' => 'settings#widget', as: :widget_settings
    get 'settings/i18n' => 'settings#i18n', as: :i18n_settings
    get 'settings/email' => 'settings#email', as: :email_settings
    get 'settings/integration' => 'settings#integration', as: :integration_settings
    get 'settings/profile' => 'settings#profile', as: :profile_settings

    get 'notifications' => 'settings#notifications', as: :notifications
    put 'update_notifications' => 'settings#update_notifications', as: :update_notifications

    # Onboarding Routes
    get '/onboarding/index' => 'onboarding#index', as: :onboarding
    patch '/onboarding/update_user' => 'onboarding#update_user', as: :onboard_user
    patch '/onboarding/update_settings' => 'onboarding#update_settings', as: :onboard_settings
    get '/onboarding/complete' => 'onboarding#complete', as: :complete_onboard

    # Misc Routes
    post 'shared/update_order' => 'shared#update_order', as: :update_order
    get 'cancel_edit_post/:id/' => 'posts#cancel', as: :cancel_edit_post
    get 'users/invite' => 'users#invite', as: :invite
    put 'users/invite_users' => 'users#invite_users', as: :invite_users

    post 'posts/users' => 'posts#search', as: :user_search
    get  'posts/new_user' => 'posts#new_user', as: :new_user
    post  'posts/new_user' => 'posts#change_owner_new_user'

    resources :categories do
      resources :docs, except: [:index, :show]
    end
    resources :docs, except: [:index, :show]

    resources :images, only: [:create, :destroy]
    resources :forums# , except: [:index, :show]
    resources :users
    scope 'settings' do
      resources :api_keys, except: [:show, :edit, :update]
      resources :groups
    end
    resources :topics, except: [:delete, :edit] do
      resources :posts
    end
    resources :posts
    get '/posts/:id/raw' => 'posts#raw', as: :post_raw
    get '/dashboard' => 'dashboard#index', as: :dashboard
    get '/reports/team' => 'reports#team', as: :team_reports
    get '/reports/groups' => 'reports#groups', as: :group_reports
    get '/reports' => 'reports#index', as: :reports

    root to: 'dashboard#index'
  end

  mount API::Base, at: "/"
  mount GrapeSwaggerRails::Engine => '/api/v1/api_doc'

  # Receive email from Griddler
  mount_griddler

  # Mount attachinary
  mount Attachinary::Engine => "/attachinary"

end

JBBar-Helpy/app/models/api_key.rb
# == Schema Information
#
# Table name: api_keys
#
#  id           :integer          not null, primary key
#  access_token :string
#  user_id      :integer
#  name         :string
#  date_expired :datetime
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class ApiKey < ActiveRecord::Base
  before_validation :generate_access_token, on: :create

  belongs_to :user
  validates :access_token, uniqueness: true
  scope :active, -> { where(date_expired: nil) }


  def expired?
    self.date_expired.present?
  end

  private

    def generate_access_token
      self.access_token = SecureRandom.hex
    end #while self.class.exists?(access_token: access_token)

end

JBBar-Helpy/app/controllers/admin/api_keys_controller.rb
# == Schema Information
#
# Table name: api_keys
#
#  id           :integer          not null, primary key
#  access_token :string
#  user_id      :integer
#  name         :string
#  date_expired :datetime
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Admin::ApiKeysController < Admin::BaseController

  before_action :set_user

  # Restrict API token generation to admin and agents only for now
  before_action :verify_agent

  layout 'admin-settings'

  def index
    @api_keys = @user.api_keys.all.order(date_expired: :desc)
    @api_key = ApiKey.new
  end

  def create
    @api_key = ApiKey.new(api_key_params)
    # @api_key.user_id = @user.id
    if @api_key.save
      render
    end
  end

  def destroy
    @api_key = @user.api_keys.where(id: params[:id]).first
    @api_key.update! date_expired: Time.current
  end

  protected

  def set_user
    # An admin should be able to view others API keys
    if current_user.is_admin?
      @user = params[:api_key].present? ? User.find(params[:api_key][:user_id]) : current_user
    else # An agent should be able to view their own API keys only
      @user = current_user
    end
  end

  private

  def api_key_params
    params.require(:api_key).permit(
    :name,
    :user_id
  )
  end


end

JBBar-Helpy/app/helpers/api_keys_helper.rb
# == Schema Information
#
# Table name: api_keys
#
#  id           :integer          not null, primary key
#  access_token :string
#  user_id      :integer
#  name         :string
#  date_expired :datetime
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

module ApiKeysHelper
end

JBBar-Helpy/app/views/admin/api_keys/_api_key.html.erb
<tr class="api_key_<%= api_key.id %> <%= 'less-important' if api_key.expired? %>">
  <td><%= api_key.name %></td>
  <td><%= api_key.access_token %></td>
  <% if api_key.expired? %>
    <td class="pull-right"><%= t("expired", default: "Expired") %></td>
  <% else %>
    <td class="expire-link-<%= api_key.id %> pull-right"><%= link_to t('expire_token', default: "Expire"), admin_api_key_path(id: api_key.id), method: :delete, remote: true, data: {confirm: t('expire_confirm', default: 'Please confirm you really want to expire this token')} %></td>
  <% end %>
</tr>

JBBar-Helpy/app/views/admin/api_keys/create.js.erb
$('.api_keys').append('<%= j render partial: "api_key", object: @api_key %>');
$('#api_key_name').val('');

JBBar-Helpy/app/views/admin/api_keys/destroy.js.erb
$('.api_key_<%= @api_key.id %>').addClass('less-important');
$('.expire-link-<%= @api_key.id %>').html("Expired");

JBBar-Helpy/app/views/admin/api_keys/index.html.erb
<% title "#{admin_title} #{t('api_keys', default: "API Keys")}" %>

<% content_for :settings do %>

<div class="admin-header">
  <h2 id="setting-header">
    <%= t('api_keys', default: "API Keys") %>
  </h2>
</div>
<div class="row content-row">

  <div class="col-md-12">

    <table id="forums" class="api_keys table-hover">
      <col width="15%">
      <col width="40%">
      <col width="40%">
      <col width="5%">
      <thead>
        <tr>
          <td class="tiny-header"><%= t('key_name', default: 'Key Name') %></td>
          <td class="tiny-header"><%= t('token', default: 'Token') %></td>
        </tr>
      </thead>
      <%= render partial: 'api_key', collection: @api_keys %>
    </table>

    <div class="add-form">
    <h4><%= t('add_key', default: 'Add a New Key') %></h4>
    <%= simple_form_for(@api_key, url: admin_api_keys_path, validate: true, remote: true, :html => { role: 'form'}) do |f| %>
      <span class="api_key-fields">
        <%= f.input :name %>
        <%= f.input :user_id, input_html: { value: @user.id }, as: :hidden %>
      </span>
      <%= f.button :submit, t("save_changes"), class: 'btn btn-warning' %>
    <% end %>
    </div>
    <br/>
    <div>
      <%= t('spec-note', default: "You can read and test out an interactive API spec at") %>:
      <%= link_to("#{request.protocol + request.host_with_port}/api/v1/api_doc", "#{request.protocol + request.host_with_port}/api/v1/api_doc") %>
    </div>
  </div>
</div>

<% end %>